### ISSUE TITLE
input flag to ignore the output cells?

### ISSUE THREAD

**Issue by DanishjeetSingh** [moisutsu/nbcat#6]
I was wondering if its possible to only cat the input cells of the notebook and ignore the output cells

sometimes the output of a cell can be super lengthy making the scroll tedious
and sometimes I just want to get an idea of whats going on in the file quickly

**Comment by moisutsu** [comment]
Thanks for the feature request!

I added it in https://github.com/moisutsu/nbcat/pull/7 and released it as [v0.2.7](https://github.com/moisutsu/nbcat/releases/tag/v0.2.7)👍
